apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-olqx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-olqx
    app.kubernetes.io/part-of: integ-app-fvfg
  name: hacbs-test-project-olqx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-olqx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-olqx
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-ytvy-tenant/integ-app-fvfg/hacbs-test-project-olqx@sha256:a81b35d83fc661d648d5a6ef37d555aae0a37bcf6ddd73d7bdf0d79db9d27e84
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
